<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Send</name>
   <tag></tag>
   <elementGuidId>7038f1fb-2b92-4319-99b6-890eda07c307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[span[contains(text(),'Send')]]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
