<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>consentCheckbox</name>
   <tag></tag>
   <elementGuidId>e3edf006-db61-40b0-8835-cdfa8cec7bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'consent__content')]//span[contains(@class,'el-checkbox__inner')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>//div[contains(@class,'consent__content')]//span[contains(@class,'el-checkbox__inner')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
