<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ddl_City</name>
   <tag></tag>
   <elementGuidId>92e13c15-25bc-40cc-b83a-7fc4dd59f79c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[1]/div/div[2]/div/div[2]/div/div/section[2]/section/ul/div/div/div[2]/div[2]/div/div/section/form/div[8]/div/div/div[1]/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
