<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_EditMobile</name>
   <tag></tag>
   <elementGuidId>f77c438b-5682-41fe-8363-914d61290dbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Mobile']&#xd;
/ancestor::div[contains(@class,'sp-my-account-setting__item')]&#xd;
//button[.//span[normalize-space()='Edit']]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
