<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_MobileValue</name>
   <tag></tag>
   <elementGuidId>4fb820e4-4431-486f-993e-b31981f02288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[normalize-space()='Mobile']&#xd;
/ancestor::div[contains(@class,'sp-my-account-setting__item')]&#xd;
//p[contains(@class,'sp-my-account-setting__item-bottom')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
